package com.luxury.concierge.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.time.Instant;
import java.util.List;
import java.util.UUID;

/**
 * Proactive gifting alert generated by the daily Spring Batch job.
 *
 * <p>Each alert is linked to a client profile and an assigned sales associate.
 * Contains AI-suggested vault items based on the client's taste vector and
 * upcoming significant dates.</p>
 *
 * <p>Note: This entity does not extend BaseEntity because the schema only
 * has {@code id} and {@code created_at} as audit fields (no updated_at,
 * version, or is_deleted).</p>
 */
@Entity
@Table(name = "concierge_alerts")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ConciergeAlert {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    @Column(name = "profile_id", nullable = false)
    private UUID profileId;

    @Column(name = "associate_id", nullable = false)
    private UUID associateId;

    @Column(name = "alert_type", length = 50)
    private String alertType;

    @Column(name = "message", columnDefinition = "TEXT")
    private String message;

    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "suggested_items", columnDefinition = "jsonb")
    private List<String> suggestedItems;

    @Column(name = "is_read")
    @Builder.Default
    private Boolean isRead = false;

    @Column(name = "created_at", updatable = false)
    private Instant createdAt;

    @PrePersist
    protected void onCreate() {
        this.createdAt = Instant.now();
    }
}
